### ISSUE TITLE
Download URL - AccessDenied

### ISSUE THREAD

**Issue by drnic** [BushtalkRadio/BushtalkClient#1]
Download link from https://bushtalkradio.com/ is not public yet

https://bushtalkradioclient-dist.s3.amazonaws.com/BushtalkClient.zip

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B30724C07E51040D</RequestId>
<HostId>
aCx8T8XCbIrAMDEll1aW6r2TTMUqnUcESt7+3WcDhmUxip+o6yPczG73rXxsGPkhMNYPlQwZP+c=
</HostId>
</Error>
```

**Comment by alpatchino** [comment]
Hi drnic, thanks for pointing this out to us. We've updated the link to redirect you to our flightsim.to page.

Thanks!
