### ISSUE TITLE
MSFS client crashes when BushTalkClient is in Community folder

### ISSUE THREAD

**Issue by EgilSandfeld** [BushtalkRadio/BushtalkClient#2]
As title says, whenever I add [BushTalkClient](https://i.imgur.com/yskCgAC.png) to MSFS and start MSFS, it crashes the sim after loading into the world. Exactly, it's crashing when I press the "Read to fly" after it finishes loading, and my guess is that that's where the in-game panels are being loaded. Once I removed the client from Community folder all is well again. 

Finally, I had the BT website open in my browser as I pressed Ready to Fly, so not sure if that's causing issues, as when I removed the client I also closed the browser.

This is the client that I'm using.
[bushtalkradio-client.zip](https://github.com/BushtalkRadio/BushtalkClient/files/6016236/bushtalkradio-client.zip)

**Comment by alpatchino** [comment]
Hi Egil,

Thanks for raising this. Are you still having issues with the client?

For the time being, you could use [our old python client ](https://github.com/BushtalkRadio/BushtalkClient#im-having-issues-with-the-new-cockpit-client--i-prefer-the-external-client) while we investigate the issue.

Kind regards

**Comment by bam2000** [comment]
for me its the same issue, would love to have it working.

**Comment by EgilSandfeld** [comment]
> Hi Egil,
> 
> Thanks for raising this. Are you still having issues with the client?
> 
> For the time being, you could use [our old python client ](https://github.com/BushtalkRadio/BushtalkClient#im-having-issues-with-the-new-cockpit-client--i-prefer-the-external-client) while we investigate the issue.
> 
> Kind regards

I do still have these issues yes.
I've tried with a clean BTC in the Community folder, also tried without credentials in CustomPanel.js and with. Tried with and without Dev Mode enabled. Tried with and without VR mode. Even tried changing the password for BT on your website. Nothing changed. It's crashing when clicking the "Ready to fly". 

Flying the Carenado Mooney Ovation (not that it should matter)

Only getting this from Event Viewer:

`Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x6038d404
Faulting module name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x6038d404
Exception code: 0xc0000005
Fault offset: 0x00000000022e51e0
Faulting process id: 0x1e58
Faulting application start time: 0x01d71429af08205e
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.13.17.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.13.17.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Report Id: 6ef2482e-7cd5-472b-99ef-c6b67abc8fb1
Faulting package full name: Microsoft.FlightSimulator_1.13.17.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App`

Again, if I remove BTC from the Community folder there are no crashes

**Comment by clinzy25** [comment]
I'm having the same issue

**Comment by Gridfield** [comment]
Hello - Also with the same issue but I've managed to narrow it down to a conflict with another mod namely VFRmap for VR. When both of those are running at the same time I get the crash - however when using either or independently it seems to work as intended. 

https://github.com/Christian1984/vfrmap-for-vr

**Comment by EgilSandfeld** [comment]
Nice find! I run the same VFRMap for VR, so that's probably why.

**Comment by bam2000** [comment]
Same here, I also have vfrmap installed

**Comment by alpatchino** [comment]
Thank you to everyone in this thread, this has really helped me out. I was unable to reproduce the issue before but I should have an easier time now. I'll let you guys know once I've pushed an update.

For the time being, use the external client if you'd like to use VFRMap at the same time.

Kind regards

**Comment by alpatchino** [comment]
Hey guys, really sorry about the delay but I've fixed the issue!

https://flightsim.to/file/7898/bushtalk-radio-client-audio-tours-from-your-cockpit

Join our Discord if you have any questions! https://discord.gg/ZcGgw9mUqA
